title: NewRock Wireless | Shop Smartphones,Tablets,Smart watches online
url: "https://50stateswireless-jpg.github.io"
baseurl: "/newrock-wireless"

defaults:
  - scope:
      path: "_layouts/default.html"
    values:
      layout: "default"
